### ISSUE TITLE
cannot identify image file <_io.BytesIO object at 0x7f2d80b2e770>

### ISSUE THREAD

**Issue by zzw1123** [aelnouby/Text-to-Image-Synthesis#22]
Thanks for your contribution!
But when I run the code, an error occurs:

Traceback (most recent call last):
  File "runtime.py", line 42, in <module>
    trainer.train(args.cls)
  File "/home/zzw/program/text2img/text-to-Image-Synthesis-pytorch/trainer.py", line 65, in train
    self._train_wgan(cls)
  File "/home/zzw/program/text2img/text-to-Image-Synthesis-pytorch/trainer.py", line 103, in _train_wgan
    sample = next(data_iterator)
  File "/home/zzw/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/zzw/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/home/zzw/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zzw/program/text2img/text-to-Image-Synthesis-pytorch/txt2image_dataset.py", line 46, in __getitem__
    right_image = Image.open(io.BytesIO(right_image)).resize((64, 64))
  File "/home/zzw/.local/lib/python2.7/site-packages/PIL/Image.py", line 2590, in open
    % (filename if filename else fp))
**IOError: cannot identify image file <_io.BytesIO object at 0x7f1be1801770>**

My Pillow version is 5.1.0, and it seems like something related to the version.
Could anyone help me out?

**Comment by Rakshith-Manandi** [comment]
Were you able to fix this? I'm facing the same issue.

**Comment by jingliao132** [comment]
I modified 'data=np.void(img)' in convert_cub_to_hd5_script.py(line 63) to 'data=np.array(img)', and reinstall the pil, then it works. I think the problem is related to the content of 'right_image' in hdf5 file. You can run a simple test on your hdf5 file:

dataset = h5py.File(PATH_TO_HDF5FILE, 'r')    # PATH_TO_HDF5FILE is the path of birds.hdf5
dataset_keys = [str(k) for k in dataset['train'].keys()]
example_name = self.dataset_keys[0]
example = self.dataset['train'][example_name]
byte_image = bytes(np.array(example['img']))
image = Image.open(io.BytesIO(byte_image))
image.show()

Hope it can help

**Comment by Hanzy1996** [comment]
I had the same question. But bug disappears when I use python3.5.

**Comment by s-a-c-h-i-n** [comment]
Run the code in python3.

**Comment by abdulla19851985** [comment]
Were you able to fix this? I'm facing the same issue
