### ISSUE TITLE
Can't Use flowers.hdf5

### ISSUE THREAD

**Issue by xianyu101** [aelnouby/Text-to-Image-Synthesis#35]
When I  want to use the data file provided by author,my IDE report bug as "RuntimeError: Unable to get group info (wrong B-tree signature)" below.
`
import h5py
f = h5py.File('flowers.hdf5', 'r')
for k in f.keys():
    print(f["test"])
` 
`
Traceback (most recent call last):
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "F:\Anaconda\lib\site-packages\h5py\_hl\group.py", line 623, in __repr__
    r = '<HDF5 group %s (%d members)>' % (namestr, len(self))
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "F:\Anaconda\lib\site-packages\h5py\_hl\group.py", line 443, in __len__
    return self.id.get_num_objs()
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5g.pyx", line 336, in h5py.h5g.GroupID.get_num_objs
RuntimeError: Unable to get group info (wrong B-tree signature)
`
![K(KP56RSNROTS2XKJ`9JXO9](https://user-images.githubusercontent.com/44837492/167993501-b7991ff0-aac1-4b71-a8ce-c3ca19258571.png)

Then I use vitables to check if there has any problems in this datafile,the result is that i can only see the groups named train,test,valid without dataset inside like this .
![%5PSEASB4A((IAP KB5{P0Q](https://user-images.githubusercontent.com/44837492/167992800-e699e2e8-7c2d-4241-ac1e-8d01a13b13bd.png)

I am a freshman in using such things.Could anyone tell me where is my problem?

**Comment by xianyu101** [comment]
There may have some problems within downloading.I downloaded data file again and it worked well.
