### ISSUE TITLE
TypeError;function takes exactly 5 arguments (1 given)

### ISSUE THREAD

**Issue by Xuchenfeng714** [aelnouby/Text-to-Image-Synthesis#7]
Hi!
I have met a very weird problem that the model could be trained several times but soon it came into error below.
hope for your reply!
Epoch: 0, d_loss= 2.205419, g_loss= 31.352011, D(X)= 0.381197, D(G(X))= 0.543290
Epoch: 0, d_loss= 1.640341, g_loss= 30.674690, D(X)= 0.512067, D(G(X))= 0.349348
Epoch: 0, d_loss= 1.334773, g_loss= 34.140278, D(X)= 0.618809, D(G(X))= 0.341588
Traceback (most recent call last):
  File "runtime.py", line 43, in <module>
    trainer.train(args.cls)
  File "/home/jurh/disk2/liupeng/text2image_3/Text-to-Image-Synthesis/trainer.py", line 67, in train
    self._train_gan(cls)
  File "/home/jurh/disk2/liupeng/text2image_3/Text-to-Image-Synthesis/trainer.py", line 177, in _train_gan for sample in self.data_loader:
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 187, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch raise batch.exc_type(batch.exc_msg)
 TypeError: function takes exactly 5 arguments (1 given)

**Comment by aelnouby** [comment]
Did you download the hd5 file provided in readme or created them yourself ? It seems there is a problem with fetching next batch with the dataloader

**Comment by Xuchenfeng714** [comment]
Yes,I used the hd5 file provided in readme directly to reappear your code,then I met this problem and didn't know how to solve it.

**Comment by Xuchenfeng714** [comment]
Oh!I created a hd5 file myself just now and then solved it.Maybe because the hd5 file provided in readme is so large so that my system can not handle it.
Also thank u for your reply!

**Comment by aelnouby** [comment]
Glad it worked, good luck
