### ISSUE TITLE
typeError during data loading

### ISSUE THREAD

**Issue by tiagd** [aelnouby/Text-to-Image-Synthesis#9]
I ran 'python runtime.py --type=gan' and got below error:

File "runtime.py", line 42, in <module>
    trainer.train(args.cls)
  File "/private/home/xjwang/twoDomainGAN-pytorch/Text-to-Image-Synthesis/trainer.py", line 67, in train
    self._train_gan(cls)
  File "/private/home/xjwang/twoDomainGAN-pytorch/Text-to-Image-Synthesis/trainer.py", line 295, in _train_gan
    for sample in self.data_loader:
  File "/public/apps/anaconda3/4.3.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 212, in __next__
    return self._process_next_batch(batch)
  File "/public/apps/anaconda3/4.3.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 239, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/public/apps/anaconda3/4.3.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 41, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/public/apps/anaconda3/4.3.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 41, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/private/home/xjwang/twoDomainGAN-pytorch/Text-to-Image-Synthesis/txt2image_dataset.py", line 42, in __getitem__
    right_image = bytes(np.array(example['img']))
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by aelnouby** [comment]
Did you download the hd5 file provided in ReadMe or converted the data yourself ? It seems that `example` variable here is not a dictionary for some reason that's why it complains about indexing with a string

**Comment by tiagd** [comment]
changed to use python2.7 and solved the problem.
